server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  absolute_redirect off;

  location = / {
    return 302 /costea-demo/;
  }

  location /costea-demo/ {
    try_files $uri $uri/ /costea-demo/index.html;
  }
}
